# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Blog"
  description: "Section showing blog cards on a carousel. Click to see blog or more."
  icon: "view_carousel"
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  background_color: "#f1f1f1"
  heading: 
    _bookshop_name: generic/heading
    title: "BLOG"
    title_color: "#333"
    subtitle: "Dantes remained confused and silent by this explanation of the thoughts which had unconsciously Dantes remained confused and silent by this explanation of the thoughts which had unconsciously "
    subtitle_color: "#333"
    line_color: "#80d6a3"
  link_color: '#80d6a3'

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  background_color: "#f1f1f1"
  heading: 
    _bookshop_name: generic/heading
    title: "BLOG"
    subtitle: "Dantes remained confused and silent by this explanation of the thoughts which had unconsciously Dantes remained confused and silent by this explanation of the thoughts which had unconsciously "
    title_color: "#333"
    subtitle_color: "#333"
    line_color: "#80d6a3"
  link_color: '#80d6a3'


# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
