# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Team"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  background_color: "#fff"
  heading: 
    title: 
    subtitle: 
    title_color: "#333"
    subtitle_color: "#6d6969"
    line_color: "#80d6a3"
  team:
    - name: 
      role: 
      image: 
      image_alt: 
      description: 
      hover_border_color: "#80d6a3"
      icon:
      icon_color: "#80d6a3"
    - name: 
      role: 
      image: 
      image_alt: 
      description: 
      hover_border_color: "#80d6a3"
      icon:
      icon_color: "#80d6a3"
    - name: 
      role: 
      image: 
      image_alt: 
      description:
      hover_border_color: "#80d6a3"
      icon:
      icon_color: "#80d6a3"


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  background_color: "#fff"
  heading: 
    _bookshop_name: generic/heading
    title: "CREATIVE TEAM"
    subtitle: "Dantes remained confused and silent by this explanation of the thoughts which had unconsciously"
    title_color: "#333"
    subtitle_color: "#333"
    line_color: "#80d6a3"
  team:
    - name: Tania Roberts
      role: Manager
      image: "/img/team1.jpg"
      image_alt: "Tania Roberts smiling at the camers, weraing a black and white striped blazer over a black top. Gold necklace with small round pendant. A glass door or wall can be seen in the background."
      description: "Dantes remained confused and silent by this explanation of the thoughts which had unconsciously"
      hover_border_color: "#80d6a3"
      icon: "sparkles-sharp"
      icon_color: "#80d6a3"
    - name: Greg McGregor
      role: Team Member
      image: "/img/team2.jpg"
      image_alt: "Greg McGregor slightly smiling at the camera. He is wearing thick framed glasses, navy dress jackets and a white shirt."
      description: "Dantes remained confused and silent by this explanation of the thoughts which had unconsciously"
      hover_border_color: "#80d6a3"
      icon: "sparkles-sharp"
      icon_color: "#80d6a3"
    - name: Ellen Allan
      role: Assistant
      image: "/img/team3.jpg"
      image_alt: "Ellen Allan smiling at the camera. She is wearing a grey jacket with white shirt. She is holding a silver laptop in her lap, sitting in a window frame with an orange wall behind her on one side and the window on the other showing a view of an office building."
      description: "Dantes remained confused and silent by this explanation of the thoughts which had unconsciously"
      hover_border_color: "#80d6a3"
      icon: "sparkles-sharp"
      icon_color: "#80d6a3"

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
