# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Portfolio"
  description: ""
  icon: "cases"
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  background_color: "#fff"
  link_color: '#80d6a3'
  heading: 
    title: 
    subtitle: 
    title_color: "#333"
    subtitle_color: "#333"
    line_color: "#80d6a3"
  projects: 
    - bookshop:generic/projects-card

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  background_color: "#fff"
  link_color: '#80d6a3'
  heading: 
    _bookshop_name: generic/heading
    title: "LATEST WORKS"
    subtitle: "Dantes remained confused and silent by this explanation of the thoughts which had unconsciously"
    title_color: "#333"
    subtitle_color: "#333"
    line_color: "#80d6a3"
  projects: 
    - bookshop:generic/projects-card


# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
