# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Pricing-table"
  description: "Three columns to display pricing details of three plans"
  icon: "view_week"
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  background_color: "#80d6a3"
  heading: 
    title: 
    title_color: "#333"
    subtitle: 
    subtitle_color: "#333"
    line_color: "#fff"
  price_card:
    - title: 
      currency_unit: 
      price: 
      frequency: 
      list_1: 
      list_2: 
      list_3: 
      list_4: 
      list_5: 
      list_6: 
      button: bookshop:generic/button
      text_color: "#fff"
      border_color: "#fff"



# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  background_color: "#80d6a3"
  heading: 
    title: "PRICING TABLE"
    subtitle: "Dantes remained confused and silent by this explanation of the thoughts which had unconsciously Dantes remained confused and silent by this explanation of the thoughts which had unconsciously "
    title_color: "#333"
    subtitle_color: "#333"
    line_color: "#fff"
  price_card:
    - title: "STARTER PACK"
      currency_unit: "$"
      price: 40
      frequency: " /month"
      list_1: "Unlimited Downloads"
      list_2: "Unlimited Uploads"
      list_3: "Unlimited Email Accounts"
      list_4: "Email Forwards"
      list_5: "Cloud Storage"
      list_6: "Screen Share"
      button: bookshop:generic/button
      text_color: "pink"
      border_color: "purple"
    - title: "MEDIUM PACK"
      currency_unit: "$"
      price: 60
      frequency: " /month"
      list_1: "Unlimited Downloads"
      list_2: "Unlimited Uploads"
      list_3: "Unlimited Email Accounts"
      list_4: "Email Forwards"
      list_5: "Cloud Storage"
      list_6: "Screen Share"
      button: bookshop:generic/button
      text_color: "pink"
      border_color: "purple"
    - title: "EXPERIENCED PACK"
      currency_unit: "$"
      price: 80
      frequency: " /month"
      list_1: "Unlimited Downloads"
      list_2: "Unlimited Uploads"
      list_3: "Unlimited Email Accounts"
      list_4: "Email Forwards"
      list_5: "Cloud Storage"
      list_6: "Screen Share"
      button: bookshop:generic/button
      text_color: "pink"
      border_color: "purple"

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
