# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Counter"
  description: "Section showing some fun number with an icon"
  icon: "pin"
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  background_color: "#444"
  heading: 
    title: 
    title_color: "#fff"
    subtitle: 
    subtitle_color: "#fff"
    line_color: "#80d6a3"
  numbers:
    - number: 
      prefix: 
      suffix: 
      text: 
      number_color: "#fff"
      icon:
      icon_color: "#80d6a3"
  image: 
  image_alt: 


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  background_color: "#444"
  heading: 
    _bookshop_name: generic/heading
    title: "FUN FACTS"
    subtitle: "Dantes remained confused and silent by this explanation of the thoughts which had unconsciously Dantes remained confused and silent by this explanation of the thoughts which had unconsciously "
    title_color: "#333"
    subtitle_color: "#333"
    line_color: "#80d6a3"
  numbers:
    - number: 136
      prefix: 
      suffix: "K"
      text: "Lines Coded"
      number_color: "#fff"
      icon: "code-sharp"
      icon_color: "#80d6a3"
    - number: 7800
      prefix: 
      suffix: "+"
      text: "Lines Deleted"
      number_color: "#fff"
      icon: "cut-sharp"
      icon_color: "#80d6a3"
    - number: 698
      prefix: 
      suffix: 
      text: "Hours Spent"
      icon: "alarm-sharp"
      icon_color:
    - number: 432
      prefix: 
      suffix: "cups"
      text: "Coffee Drunk"
      number_color: "#fff"
      icon: "cafe-sharp"
      icon_color: "#80d6a3"
  image: '/img/desk.jpg'
  image_alt: 'Birds eye view of table with desk items'


# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:

