# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Features"
  description: "grid with icon, subtitle and blurbs for displaying features or services"
  icon: "view_compact"
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  background_color: "#fff"
  heading: 
    title: 
    title_color: "#333"
    subtitle: 
    subtitle_color: "#6d6969"
    line_color: "#80d6a3"
  features:
    - icon:
      icon_color:
      heading: 
      features_heading_color: "#333"
      text: 
      features_text_color: "#6d6969"


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  background_color: "#fff"
  heading: 
    _bookshop_name: generic/heading
    title: "OUR BEST SERVICES"
    subtitle: "Dantes remained confused and silent by this explanation of the thoughts which had unconsciously"
    title_color: "#333"
    subtitle_color: "#6d6969"
    line_color: "#80d6a3"
  features:
    - icon: "easel-sharp"
      icon_color: "#80d6a3"
      heading: "Responsive Design"
      text: "Now with range. Lorem ipsum dolor sit amet, consectetur adipisic-ing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim"
      features_heading_color: "#333"
      features_text_color: "#6d6969"
    - icon: "color-fill-sharp"
      icon_color: "#80d6a3"
      heading: "Outstanding Animation"
      text: "Lorem ipsum dolor sit amet, consectetur adipisic-ing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim"
      features_heading_color: "#333"
      features_text_color: "#6d6969"
    - icon: "brush-sharp"
      icon_color: "#80d6a3"
      heading: "Unlimited Colors"
      text: "Lorem ipsum dolor sit amet, consectetur adipisic-ing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim"
      features_heading_color: "#333"
      features_text_color: "#6d6969"

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
