# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Testimonial"
  description: "Share some testimonials: picture and quote"
  icon: "grid_view"
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  background_color: "#fff"
  heading: 
    title: 
    subtitle:  
    title_color: 
    subtitle_color: 
    line_color: 
  testimonials:
    - name: 
      text: 
      image: 
      image_alt: 
    - name: 
      text: 
      image: 
      image_alt: 
    - name: 
      text: 
      image: 
      image_alt: 
    - name: 
      text: 
      image: 
      image_alt: 

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  background_color: "#fff"
  heading: 
    _bookshop_name: generic/heading
    title: "TESTIMONIALS"
    subtitle: "Dantes remained confused and silent by this explanation of the thoughts which had unconsciously"
    title_color: "#333"
    subtitle_color: "#333"
    line_color: "#80d6a3"
  testimonials:
    - name: "Jonathon Andrew"
      text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commo"
      image: "/img/testimonial1.jpg"
      image_alt: "Jonathan smiling at the camera wearing a grey top with blue shirt collar peaking out the top."
    - name: "Amelia Scott"
      text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commo"
      image: "/img/testimonial2.jpg"
      image_alt: "Amelia smiling at the camera, wearing red lipstick and black singlet."
    - name: "Harry Potter"
      text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commo"
      image: "/img/testimonial3.jpg"
      image_alt: "Harry wearing his wizarding hat, glasses and dark hoodie."
    - name: "Anne Lewis"
      text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commo"
      image: "/img/testimonial4.jpg"
      image_alt: "Anne smiling at the camera, wearing a white t-shirt and hair tied in a messy bun."
      

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
